# NUMPY

In [50]:
import numpy as np
#Array

In [2]:
s =[1,2,3,4]
h =[]
for i in s:
    h.append(2*i)
print (h)

[2, 4, 6, 8]


In [3]:
arr = np.array(s)

In [5]:
print(arr*2)

[2 4 6 8]


In [6]:
pip install numpy


[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [7]:
pip install --upgrade numpy


[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [10]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [11]:
arr2 #matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [13]:
arr2[0]

array([1, 2, 3])

In [15]:
print(arr2[0][1])

2


In [16]:
arr2[0:1]

array([[1, 2, 3]])

In [17]:
arr2[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr2[0:2,2]

array([3, 6])

In [24]:
arr2 [0:2, 0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr2 [0:2, 2:]

array([[3],
       [6]])

In [27]:
w = [1,2,3,4,5,6,7,8,9,10]
arr3 = np.array(w)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr3.reshape((2,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
arr3.reshape((5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [32]:
arr4 = np.array(w).reshape((5,2))
arr4

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [36]:
a =np.array(range(1,101))

In [37]:
a.size

100

In [38]:
a.reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [40]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [41]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
pip install --upgrade pip

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 28.0 MB/s  0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 26.1.2
    Uninstalling pip-26.1.2:
      Successfully uninstalled pip-26.1.2
Note: you may need to restart the kernel to use updated packages.


# pandas

In [44]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [45]:
pip install pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 46.9 MB/s  0:00:00eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [48]:
import pandas as pd
# Series and Dataframe

In [53]:
names = ["sam", "don", "giri"]

In [55]:
pd.Series(names)

0     sam
1     don
2    giri
dtype: str

In [56]:
pd.Series(names, index = [1,2,3])

1     sam
2     don
3    giri
dtype: str

In [59]:
marks = [12,32,42]
pd.Series(marks, index = names)

sam     12
don     32
giri    42
dtype: int64